package com.macro.mall.mbg.mapper;

import com.macro.mall.model.UmsMemberRuleSetting;
import com.macro.mall.model.UmsMemberRuleSettingExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UmsMemberRuleSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    long countByExample ( UmsMemberRuleSettingExample example );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    int deleteByExample ( UmsMemberRuleSettingExample example );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    int deleteByPrimaryKey ( Long id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    int insert ( UmsMemberRuleSetting record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    int insertSelective ( UmsMemberRuleSetting record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    List<UmsMemberRuleSetting> selectByExample ( UmsMemberRuleSettingExample example );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    UmsMemberRuleSetting selectByPrimaryKey ( Long id );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    int updateByExampleSelective ( @Param("record") UmsMemberRuleSetting record, @Param("example") UmsMemberRuleSettingExample example );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    int updateByExample ( @Param("record") UmsMemberRuleSetting record, @Param("example") UmsMemberRuleSettingExample example );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    int updateByPrimaryKeySelective ( UmsMemberRuleSetting record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Wed Apr 29 21:35:42 CST 2020
     */
    int updateByPrimaryKey ( UmsMemberRuleSetting record );
}